#include <string>
#include <iostream>
#include <sstream>
#include <ostream>
#include <fstream>
#include "module_common.h"

using namespace std;

namespace sight {
namespace common {

/*******************
 ***** context *****
 *******************/

// Loads this context from the given properties map. The names of all the fields are assumed to be prefixed
// with the given string.
module::context::context(properties::iterator props, std::string prefix) {
  
  int numCfgKeys = properties::getInt(props, txt()<<prefix<<"numCfgKeys");
  for(int i=0; i<numCfgKeys; i++) {
    configuration[properties::get(props, txt()<<prefix<<"key_"<<i)] = 
                              attrValue(properties::get(props, txt()<<prefix<<"val_"<<i), attrValue::unknownT);
                                        //(attrValue::valueType)properties::getInt(props, txt()<<prefix<<"type_"<<i));
  }
}

// Returns the properties map that describes this context object.
// The names of all the fields in the map are prefixed with the given string.
map<string, string> module::context::getProperties(std::string prefix) const {
  map<string, string> pMap;
  int i=0;
  pMap[txt()<<prefix<<"numCfgKeys"] = txt()<<configuration.size();
  for(std::map<std::string, attrValue>::const_iterator cfg=configuration.begin(); cfg!=configuration.end(); cfg++, i++) {
    pMap[txt()<<prefix<<"key_"<<i]  = cfg->first;
    pMap[txt()<<prefix<<"val_"<<i]  = cfg->second.serialize();
  }
  return pMap;
}

// Returns a human-readable string that describes this context
std::string module::context::str() const {
  ostringstream s;
  s << "[context :"<<endl;
  for(map<string, attrValue>::const_iterator c=configuration.begin(); c!=configuration.end(); c++) {
    if(c!=configuration.begin()) s << " ";
    s << "("<<c->first<<": "<<c->second.getAsStr()<<")";
  }
  s << "]";
  return s.str();
}

// Returns a string encoding of the key information of a context attribute:
// moduleClass - the class that inherits from module that produced this attribute
// ctxtGrouping - the name of the grouping of context attributes within the attributes generated by the 
//    module class. This may be a given input (e.g. input0) or the configuration options of a compModule.
// attrName - the name of the context attribute itself.
std::string module::encodeCtxtName(const std::string& moduleClass, const std::string& ctxtGrouping, const std::string& attrName) {
  return txt()<<escapedStr(moduleClass,  ":", escapedStr::unescaped).escape()<<":"<<
                escapedStr(ctxtGrouping, ":", escapedStr::unescaped).escape()<<":"<<
                escapedStr(attrName,     ":", escapedStr::unescaped).escape();
}

// Given a string encoded by encodeCtxtName(), sets moduleClass, ctxtGrouping and attrName to their original values
void module::decodeCtxtName(const std::string& encoded, std::string& moduleClass, std::string& ctxtGrouping, std::string& attrName) {
  escapedStr e(encoded, ":", escapedStr::escaped);
  vector<string> fields = e.unescapeSplit(":");
  cout << "encoded="<<encoded<<" #fields="<<fields.size()<<endl;
  assert(fields.size()>=2);
  moduleClass  = fields[0];
  ctxtGrouping = fields[1];
  if(fields.size()>=3) attrName = fields[2];
  else                 attrName = "";
}

}; // namespace common
}; // namespace sight